config/routes.rb
Rails.application.routes.draw do
  root "kittens#index"
  resources :kittens
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
  validates :name, :age, :cuteness, :softness, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  before_action :set_kitten, except: %i[index new create]

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html
      format.json { render json: @kittens }
    end
  end

  def new
    @kitten = Kitten.new
  end

  def show
    respond_to do |format|
      format.html
      format.json { render json: @kitten }
    end
  end

  def create
    @kitten = Kitten.new(kitty_params)

    if @kitten.save
      redirect_to @kitten, notice: 'Kitten Successfully Created.'
    else
      render :new
    end
  end

  def update
    if @kitten.update(kitty_params)
      redirect_to @kitten, notice: 'Kitten successfully updates.'
    else
      render :edit
    end
  end

  def destroy
    if @kitten.destroy
      redirect_to kittens_path, notice: 'Kitten successfully destroyed.'
    else
      redirect_back fallback_location: root_path, alert: 'Failed to destroy the kitten.', status: :see_other
    end
  end

  private

  def set_kitten
    @kitten = Kitten.find(params[:id])
  end

  def kitty_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_flash.html.erb
<% flash.each do |_type, msg| %>
  <div class="container p-3 text-center alert alert-info">
    <%= msg %>
  </div>
<% end %>

app/views/kittens/_form.html.erb
<% if @kitten.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@kitten.errors.count, "error") %></h2>
    <ul>
      <% @kitten.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<%= render "flash" %>

<%= form_for @kitten do |f| %>
  <div class="col-md-3 p-5">
    <%= f.label :name, "Kitty Name", class: 'mb-2' %>
    <%= f.text_field :name, class: 'form-control mb-3' %>

    <%= f.label :age, "Kitty Age", class: 'mb-2' %>
    <%= f.number_field :age, class: 'form-control mb-3' %>

    <%= f.label :cuteness, "Kitty Cuteness", class: 'mb-2' %>
    <%= f.number_field :cuteness, class: 'form-control mb-3' %>

    <%= f.label :softness, "Kitty Softness", class: 'mb-2' %>
    <%= f.number_field :softness, class: 'form-control mb-3' %>

    <%= f.submit 'Save', class: 'btn btn-primary form-control'%>
  </div>
<% end %>

<% if @kitten.persisted? %>
  <%= button_to 'Delete', kitten_path(@kitten), class: 'btn btn-danger mt-3', form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>
<% end %>

app/views/kittens/edit.html.erb
<div class="container">
  <h1>Kittens#edit</h1>
  <%= render  "form" %>
</div>

app/views/kittens/index.html.erb
<div class="container">
  <h1 class="bg-info-subtle text-center p-2">Kittens</h1>

  <%= render "flash" %>

  <p><%= link_to 'New Kitty', new_kitten_path  %></p>

  <% @kittens.each do |kitten| %>
    <div class="bg-warning-subtle p-3 mb-3">
      <p>Kitty Name: <%= content_tag :span, kitten.name, class: 'fw-semibold' %>
        <%= link_to "Show", kitten_path(kitten) %>
        <%= button_to "Delete", kitten_path(kitten), class: 'btn btn-danger', form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>
      </p>
    </div>
  <% end %>
</div>

app/views/kittens/new.html.erb
<div class="container">
  <h1>Kittens#new</h1>
  <%= render  "form" %>
</div>

app/views/kittens/show.html.erb
<div class="container p-3">
  <%= render "flash" %>

  <%= content_tag :h2, "Kitty id: #{@kitten.id}"%>

  <p>Kitty name: <span class="fw-semibold"><%= @kitten.name %></span></p>
  <p>Kitty Age: <span class="fw-semibold"><%= @kitten.age %></span></p>
  <p>Kitty Cuteness: <span class="fw-semibold"><%= @kitten.cuteness %></span></p>
  <p>Kitty Softness: <span class="fw-semibold"><%= @kitten.softness %></span></p>
  <p class="fs-6 fw-lighter">Created at: <span class="fs-6 fw-lighter"><%= @kitten.created_at.strftime('%Y-%m-%d') %></span></p>

  <p><%= link_to 'Edit Kitty', edit_kitten_path(@kitten) %></p>
  <p><%= link_to 'Home', kittens_path %></p>

  <div>
    <%= button_to "Delete", kitten_path(@kitten), class: 'btn btn-danger', form: { data: { turbo_confirm: "Are you sure?" } }, method: :delete %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>